services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    env_file:
      - .env
#    user: "${UID:-1000}:${GID:-1000}"   # Run as your host user for file permissions [[1]]
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTT over SSL
      - "8083:8083"    # WebSocket
      - "8084:8084"    # Secure WebSocket
      - "80:18083"  # Dashboard
    volumes:
      - ./data:/opt/emqx/data
      - ./log:/opt/emqx/log
      # - ./certs:/opt/emqx/etc/certs  # Uncomment if using custom SSL certs
    networks:
      - emqx-net
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 10s
      timeout: 20s
      retries: 5
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run

networks:
  emqx-net:
    driver: bridge
