sudo chmod 777 /var/run/docker.sock
alias dps="sudo docker ps -a"
alias dimg="sudo docker images"
alias drmi="sudo docker rmi -f "
alias drm="sudo docker rm -f "
alias dup="sudo docker compose up"
alias dup-d="sudo docker compose up -d"
alias dbuild="sudo docker compose build "
alias dlog="sudo docker logs -f "
alias dbuildup="sudo docker compose up --build"
alias dbuildup-d="sudo docker compose up --build -d"
alias ddown="sudo docker compose down"
alias ddownrmi="sudo docker compose down --rmi all"
alias dprune="sudo docker image prune -f"
alias dclean="sudo docker system prune -a"
alias dcleanf="sudo docker system prune --all --volumes --force"
alias dexec="sudo docker exec -it "
